# Generated by Django 5.1.2 on 2024-11-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_app', '0006_remove_orderitem_order_remove_orderitem_product_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
    ]
